### ISSUE TITLE
More elegant way of finding the SNI

### ISSUE THREAD

**Issue by buschtoens** [buschtoens/sni#1]
Searching for the double zero byte and then doing a regex is quite hack-ish.
Though it works safely, I'd still like a more "official" way.

**Comment by jornane** [comment]
I forked your repo and rewrote most of `index.js`

https://github.com/jornane/sni/blob/1d252b5b4f37f45749048eddc7d88723900618da/index.js

**Comment by buschtoens** [comment]
Hey @jornane, awesome work! :gem: 

`sni` was one of my first modules, which I'm not really proud of in hindsight. Haha.
I added you as a collaborator for this repo. Feel free to merge your change.

What's your npm handle, so I can add you there as well? :)

**Comment by jornane** [comment]
I registered for an npm account now, username is the same as my GitHub username.

**Comment by buschtoens** [comment]
Closed by #3.
