### ISSUE TITLE
SNI as in HTTPS SNI? As in multiple domains with 1 IP?

### ISSUE THREAD

**Issue by coolaj86** [buschtoens/sni#2]
Can I use this to host multiple https sites on a single IP? Can you give an example of how to do that?

**Comment by coolaj86** [comment]
As in, how would you pipe the `net` connection to the `https` server?

**Comment by jornane** [comment]
Does this help? https://github.com/jornane/node-snip

**Comment by coolaj86** [comment]
It probably would, but I figured it out in Go, which I think is better for my purposes anyway since eventually this part will be a static server and perhaps some proxying.

https://github.com/coolaj86/golang-https-example/blob/master/serve.go#L90

(update: actually this branch has the more well-formed code https://github.com/coolaj86/golang-https-example/blob/acme-proxy/serve.go#L143)
Thanks for the follow-up.

**Comment by buschtoens** [comment]
@coolaj86 So sorry for not responding... in a year. This issue must have slipped my attention. :sweat_smile: 

Anyways, to make it clear for anyone who might stumble upon his issue:

> Can I use this to host multiple https sites on a single IP? Can you give an example of how to do that?
> As in, how would you pipe the `net` connection to the `https` server?

Yes and yes. HTTPS is regular HTTP ontop of an encrypted TLS stream. So before the actual HTTP data exchange happens, a TLS handshake is performed. The first packet send by the client contains the SNI, which can be read out by `sni(data)`.

Based on this result you can then re-route this and the following packets.

@jornane's [code](https://github.com/jornane/node-snip/blob/master/snip.js#L39-L42) illustrates this very well.
